<script src="{{ asset('themes/frontend/swiper/swiper-bundle.min.js') }}"></script>
<script src="{{ asset('themes/frontend/js/index.js') }}"></script>
<script src="{{ asset('themes/frontend/js/home.js') }}"></script>
{{-- <script src="{{ asset('themes/frontend/js/detail-page.js') }}"></script>
<script src="{{ asset('themes/frontend/js/information.js') }}"></script> --}}
{{-- <script src="{{ asset('themes/frontend/js/list-product-1.js') }}"></script> --}}
{{-- <script src="{{ asset('themes/frontend/js/list-product-2.js') }}"></script>
<script src="{{ asset('themes/frontend/js/product-detail.js') }}"></script>
<script src="{{ asset('themes/frontend/js/rangeslider.umd.min.js') }}"></script>
<script src="{{ asset('themes/frontend/js/wishlist.js') }}"></script> --}}